# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Calibration_Window.ui'
##
## Created by: Qt User Interface Compiler version 6.5.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QProgressBar,
    QPushButton, QSizePolicy, QWidget)
import ResourceFiles_rc

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(793, 520)
        Form.setStyleSheet(u"background-color: rgb(120, 22, 25);")
        self.frame_3 = QFrame(Form)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(20, 20, 761, 61))
        self.frame_3.setStyleSheet(u"background-color: rgb(255, 246, 235);\n"
"border-radius: 10px;")
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.Username_label = QLabel(self.frame_3)
        self.Username_label.setObjectName(u"Username_label")
        self.Username_label.setGeometry(QRect(70, 20, 191, 21))
        font = QFont()
        font.setFamilies([u"Elephant"])
        font.setPointSize(14)
        self.Username_label.setFont(font)
        self.Username_label.setStyleSheet(u"color: rgb(217, 66, 39);")
        self.label_5 = QLabel(self.frame_3)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(20, 10, 41, 41))
        self.label_5.setMinimumSize(QSize(1, 1))
        self.label_5.setMaximumSize(QSize(50, 50))
        self.label_5.setAutoFillBackground(False)
        self.label_5.setStyleSheet(u"color: rgb(217, 66, 39);")
        self.label_5.setPixmap(QPixmap(u":/Icons/user-circle-svgrepo-com.svg"))
        self.label_5.setScaledContents(True)
        self.label_5.setOpenExternalLinks(True)
        self.label = QLabel(self.frame_3)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(610, 10, 91, 41))
        font1 = QFont()
        font1.setFamilies([u"Forte"])
        font1.setPointSize(14)
        self.label.setFont(font1)
        self.label.setStyleSheet(u"color: rgb(217, 66, 39);\n"
"")
        self.label_2 = QLabel(self.frame_3)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(700, 10, 41, 41))
        self.label_2.setPixmap(QPixmap(u":/Images/hearthands2round.png"))
        self.label_2.setScaledContents(True)
        self.frame = QFrame(Form)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(20, 90, 761, 411))
        self.frame.setStyleSheet(u"background-color: rgb(254, 245, 234);\n"
"border-radius: 10 px;")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.frame_2 = QFrame(self.frame)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(420, 100, 231, 231))
        self.frame_2.setStyleSheet(u"border-radius: 10px;\n"
"border: 5px solid;\n"
"border-color: rgb(167, 29, 34);")
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.StayStill_label = QLabel(self.frame_2)
        self.StayStill_label.setObjectName(u"StayStill_label")
        self.StayStill_label.setGeometry(QRect(30, 140, 171, 61))
        font2 = QFont()
        font2.setFamilies([u"Montserrat Medium"])
        font2.setPointSize(20)
        self.StayStill_label.setFont(font2)
        self.StayStill_label.setStyleSheet(u"background-color: rgb(254, 245, 234);\n"
"border-color: rgb(254, 245, 234);")
        self.seconds_label = QLabel(self.frame_2)
        self.seconds_label.setObjectName(u"seconds_label")
        self.seconds_label.setGeometry(QRect(30, 30, 161, 27))
        palette = QPalette()
        brush = QBrush(QColor(0, 0, 0, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(254, 245, 234, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(0, 134, 0, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        brush3 = QBrush(QColor(99, 173, 105, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        brush4 = QBrush(QColor(0, 46, 0, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Dark, brush4)
        brush5 = QBrush(QColor(0, 62, 0, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        brush6 = QBrush(QColor(255, 255, 255, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush4)
        brush7 = QBrush(QColor(255, 255, 220, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush7)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
        brush8 = QBrush(QColor(255, 255, 255, 128))
        brush8.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush8)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush7)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush8)
#endif
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        brush9 = QBrush(QColor(0, 93, 0, 255))
        brush9.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush9)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush7)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush8)
#endif
        self.seconds_label.setPalette(palette)
        font3 = QFont()
        font3.setFamilies([u"Montserrat SemiBold"])
        font3.setPointSize(12)
        font3.setBold(True)
        self.seconds_label.setFont(font3)
        self.seconds_label.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"background-color: rgb(254, 245, 234);\n"
"border-radius: 10px;\n"
"border: 3px solid;\n"
"border-color: rgb(254, 245, 234);")
        self.seconds_label.setAlignment(Qt.AlignCenter)
        self.countdown_label = QLabel(self.frame_2)
        self.countdown_label.setObjectName(u"countdown_label")
        self.countdown_label.setGeometry(QRect(90, 70, 51, 71))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush4)
        brush10 = QBrush(QColor(255, 246, 235, 255))
        brush10.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush10)
        palette1.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette1.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette1.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush4)
        palette1.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush4)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush10)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush10)
        palette1.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette1.setBrush(QPalette.Active, QPalette.AlternateBase, brush4)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipBase, brush7)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush8)
#endif
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush10)
        palette1.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette1.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette1.setBrush(QPalette.Inactive, QPalette.ButtonText, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush10)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush10)
        palette1.setBrush(QPalette.Inactive, QPalette.Shadow, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush7)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush8)
#endif
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush10)
        palette1.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette1.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush10)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush10)
        palette1.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush9)
        palette1.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush7)
        palette1.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush8)
#endif
        self.countdown_label.setPalette(palette1)
        font4 = QFont()
        font4.setFamilies([u"Montserrat Medium"])
        font4.setPointSize(26)
        font4.setBold(False)
        self.countdown_label.setFont(font4)
        self.countdown_label.setStyleSheet(u"background-color: rgb(255, 246, 235);\n"
"color: rgb(0, 46, 0);\n"
"border-color: rgb(254, 245, 234);")
        self.exit_btn = QPushButton(self.frame)
        self.exit_btn.setObjectName(u"exit_btn")
        self.exit_btn.setGeometry(QRect(30, 350, 161, 41))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush11 = QBrush(QColor(255, 221, 188, 255))
        brush11.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Button, brush11)
        brush12 = QBrush(QColor(139, 255, 176, 255))
        brush12.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Light, brush12)
        brush13 = QBrush(QColor(115, 213, 146, 255))
        brush13.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Midlight, brush13)
        brush14 = QBrush(QColor(46, 85, 59, 255))
        brush14.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Dark, brush14)
        brush15 = QBrush(QColor(61, 114, 78, 255))
        brush15.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Mid, brush15)
        palette2.setBrush(QPalette.Active, QPalette.Text, brush)
        palette2.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette2.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush11)
        palette2.setBrush(QPalette.Active, QPalette.Window, brush11)
        palette2.setBrush(QPalette.Active, QPalette.Shadow, brush)
        brush16 = QBrush(QColor(173, 213, 186, 255))
        brush16.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.AlternateBase, brush16)
        palette2.setBrush(QPalette.Active, QPalette.ToolTipBase, brush7)
        palette2.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
        brush17 = QBrush(QColor(0, 0, 0, 128))
        brush17.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Active, QPalette.PlaceholderText, brush17)
#endif
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush11)
        palette2.setBrush(QPalette.Inactive, QPalette.Light, brush12)
        palette2.setBrush(QPalette.Inactive, QPalette.Midlight, brush13)
        palette2.setBrush(QPalette.Inactive, QPalette.Dark, brush14)
        palette2.setBrush(QPalette.Inactive, QPalette.Mid, brush15)
        palette2.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette2.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush11)
        palette2.setBrush(QPalette.Inactive, QPalette.Window, brush11)
        palette2.setBrush(QPalette.Inactive, QPalette.Shadow, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush16)
        palette2.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush7)
        palette2.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush17)
#endif
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.Button, brush11)
        palette2.setBrush(QPalette.Disabled, QPalette.Light, brush12)
        palette2.setBrush(QPalette.Disabled, QPalette.Midlight, brush13)
        palette2.setBrush(QPalette.Disabled, QPalette.Dark, brush14)
        palette2.setBrush(QPalette.Disabled, QPalette.Mid, brush15)
        palette2.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette2.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.Base, brush11)
        palette2.setBrush(QPalette.Disabled, QPalette.Window, brush11)
        palette2.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        brush18 = QBrush(QColor(92, 171, 117, 255))
        brush18.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush18)
        palette2.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush7)
        palette2.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush17)
#endif
        self.exit_btn.setPalette(palette2)
        font5 = QFont()
        font5.setFamilies([u"Montserrat Medium"])
        font5.setPointSize(9)
        font5.setBold(False)
        font5.setItalic(True)
        self.exit_btn.setFont(font5)
        self.exit_btn.setStyleSheet(u"QPushButton{\n"
"background-color: rgb(255, 221, 188);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"border: 3px solid;\n"
"border-color: rgb(167, 29, 34);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed{\n"
"border: 6px solid;\n"
"border-color: rgb(255, 132, 32);\n"
"}")
        self.label_8 = QLabel(self.frame)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(40, 360, 21, 21))
        self.label_8.setStyleSheet(u"background-color: rgb(255, 221, 188);")
        self.label_8.setPixmap(QPixmap(u":/Icons/home-1-svgrepo-com.svg"))
        self.label_8.setScaledContents(True)
        self.start_button = QPushButton(self.frame)
        self.start_button.setObjectName(u"start_button")
        self.start_button.setGeometry(QRect(110, 220, 221, 51))
        self.start_button.setFont(font3)
        self.start_button.setStyleSheet(u"QPushButton{\n"
"background-color: rgb(255, 221, 188);\n"
"border-radius: 10px;\n"
"border: 3px solid;\n"
"border-color: rgb(167, 29, 34);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed{\n"
"border: 6px solid;\n"
"border-color: rgb(255, 132, 32);\n"
"}")
        self.message_label = QLabel(self.frame)
        self.message_label.setObjectName(u"message_label")
        self.message_label.setGeometry(QRect(30, 30, 711, 41))
        font6 = QFont()
        font6.setFamilies([u"Elephant"])
        font6.setPointSize(18)
        self.message_label.setFont(font6)
        self.message_label.setStyleSheet(u"background-color: rgb(254, 245, 234);\n"
"color: rgb(217, 66, 39);")
        self.message_label.setAlignment(Qt.AlignCenter)
        self.progressBar = QProgressBar(self.frame)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(110, 160, 221, 31))
        font7 = QFont()
        font7.setFamilies([u"Montserrat ExtraBold"])
        font7.setPointSize(12)
        font7.setBold(True)
        self.progressBar.setFont(font7)
        self.progressBar.setStyleSheet(u"QProgressBar{\n"
"border-radius: 10px;\n"
"border: 3px solid;\n"
"border-color: rgb(167, 29, 34);\n"
"background-color: rgb(254, 245, 234);\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"background-color: rgb(217, 66, 39);\n"
"}")
        self.progressBar.setValue(24)
        self.progressBar.setAlignment(Qt.AlignCenter)
        self.progressBar.setTextDirection(QProgressBar.TopToBottom)
        self.frame.raise_()
        self.frame_3.raise_()

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.Username_label.setText(QCoreApplication.translate("Form", u"Username", None))
        self.label_5.setText("")
        self.label.setText(QCoreApplication.translate("Form", u"  Handy", None))
        self.label_2.setText("")
        self.StayStill_label.setText(QCoreApplication.translate("Form", u"Stay Still", None))
        self.seconds_label.setText(QCoreApplication.translate("Form", u"Seconds left:", None))
        self.countdown_label.setText(QCoreApplication.translate("Form", u"2", None))
        self.exit_btn.setText(QCoreApplication.translate("Form", u"      Back to Game", None))
        self.label_8.setText("")
        self.start_button.setText(QCoreApplication.translate("Form", u"Start Calibrating", None))
        self.message_label.setText("")
    # retranslateUi

