# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Game_Window.ui'
##
## Created by: Qt User Interface Compiler version 6.5.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QPushButton,
    QSizePolicy, QWidget)
import ResourceFiles_rc

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(795, 519)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        palette = QPalette()
        brush = QBrush(QColor(255, 253, 243, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(130, 24, 27, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(0, 134, 0, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        brush3 = QBrush(QColor(99, 173, 105, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        brush4 = QBrush(QColor(0, 46, 0, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Dark, brush4)
        brush5 = QBrush(QColor(0, 62, 0, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush5)
        brush6 = QBrush(QColor(255, 255, 255, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Text, brush6)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush6)
        palette.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        brush7 = QBrush(QColor(0, 0, 0, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush7)
        palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush4)
        brush8 = QBrush(QColor(255, 255, 220, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush7)
        brush9 = QBrush(QColor(255, 255, 255, 128))
        brush9.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush9)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush7)
        palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush7)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush9)
#endif
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush7)
        brush10 = QBrush(QColor(0, 93, 0, 255))
        brush10.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush10)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush7)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush9)
#endif
        Form.setPalette(palette)
        Form.setStyleSheet(u"background-color: rgb(130, 24, 27);")
        self.frame_3 = QFrame(Form)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(20, 20, 761, 61))
        self.frame_3.setStyleSheet(u"background-color: rgb(255, 246, 235);\n"
"border-radius: 10px;")
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.Username_label = QLabel(self.frame_3)
        self.Username_label.setObjectName(u"Username_label")
        self.Username_label.setGeometry(QRect(70, 20, 191, 21))
        font = QFont()
        font.setFamilies([u"Elephant"])
        font.setPointSize(14)
        self.Username_label.setFont(font)
        self.Username_label.setStyleSheet(u"color: rgb(217, 66, 39);")
        self.label_5 = QLabel(self.frame_3)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(20, 10, 41, 41))
        self.label_5.setMinimumSize(QSize(1, 1))
        self.label_5.setMaximumSize(QSize(50, 50))
        self.label_5.setAutoFillBackground(False)
        self.label_5.setStyleSheet(u"color: rgb(217, 66, 39);")
        self.label_5.setPixmap(QPixmap(u":/Icons/user-circle-svgrepo-com.svg"))
        self.label_5.setScaledContents(True)
        self.label_5.setOpenExternalLinks(True)
        self.label_6 = QLabel(self.frame_3)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(670, 10, 41, 41))
        self.label_6.setStyleSheet(u"color: rgb(217, 66, 39);")
        self.label_6.setPixmap(QPixmap(u":/Icons/prize-badge-with-star-and-ribbon-svgrepo-com.svg"))
        self.label_6.setScaledContents(True)
        self.label_7 = QLabel(self.frame_3)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(580, 20, 91, 21))
        self.label_7.setFont(font)
        self.label_7.setStyleSheet(u"color: rgb(217, 66, 39);")
        self.score_label = QLabel(self.frame_3)
        self.score_label.setObjectName(u"score_label")
        self.score_label.setGeometry(QRect(320, 14, 71, 31))
        palette1 = QPalette()
        brush11 = QBrush(QColor(217, 66, 39, 255))
        brush11.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush11)
        brush12 = QBrush(QColor(255, 246, 235, 255))
        brush12.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush12)
        palette1.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette1.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette1.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush11)
        palette1.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush11)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush12)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush12)
        palette1.setBrush(QPalette.Active, QPalette.Shadow, brush7)
        palette1.setBrush(QPalette.Active, QPalette.AlternateBase, brush4)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipText, brush7)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush9)
#endif
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush11)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush12)
        palette1.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette1.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush11)
        palette1.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette1.setBrush(QPalette.Inactive, QPalette.ButtonText, brush11)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush12)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush12)
        palette1.setBrush(QPalette.Inactive, QPalette.Shadow, brush7)
        palette1.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush7)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush9)
#endif
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush11)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush12)
        palette1.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette1.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush11)
        palette1.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush11)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush12)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush12)
        palette1.setBrush(QPalette.Disabled, QPalette.Shadow, brush7)
        palette1.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush10)
        palette1.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette1.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush7)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush9)
#endif
        self.score_label.setPalette(palette1)
        font1 = QFont()
        font1.setFamilies([u"Elephant"])
        font1.setPointSize(14)
        font1.setBold(False)
        self.score_label.setFont(font1)
        self.score_label.setStyleSheet(u"color: rgb(217, 66, 39);")
        self.score_value = QLabel(self.frame_3)
        self.score_value.setObjectName(u"score_value")
        self.score_value.setGeometry(QRect(400, 20, 41, 21))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush11)
        palette2.setBrush(QPalette.Active, QPalette.Button, brush12)
        palette2.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette2.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette2.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette2.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette2.setBrush(QPalette.Active, QPalette.Text, brush11)
        palette2.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette2.setBrush(QPalette.Active, QPalette.ButtonText, brush11)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush12)
        palette2.setBrush(QPalette.Active, QPalette.Window, brush12)
        palette2.setBrush(QPalette.Active, QPalette.Shadow, brush7)
        palette2.setBrush(QPalette.Active, QPalette.AlternateBase, brush4)
        palette2.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette2.setBrush(QPalette.Active, QPalette.ToolTipText, brush7)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Active, QPalette.PlaceholderText, brush9)
#endif
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush11)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush12)
        palette2.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette2.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette2.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette2.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette2.setBrush(QPalette.Inactive, QPalette.Text, brush11)
        palette2.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette2.setBrush(QPalette.Inactive, QPalette.ButtonText, brush11)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush12)
        palette2.setBrush(QPalette.Inactive, QPalette.Window, brush12)
        palette2.setBrush(QPalette.Inactive, QPalette.Shadow, brush7)
        palette2.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush4)
        palette2.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette2.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush7)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush9)
#endif
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush11)
        palette2.setBrush(QPalette.Disabled, QPalette.Button, brush12)
        palette2.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette2.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette2.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette2.setBrush(QPalette.Disabled, QPalette.Text, brush11)
        palette2.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette2.setBrush(QPalette.Disabled, QPalette.ButtonText, brush11)
        palette2.setBrush(QPalette.Disabled, QPalette.Base, brush12)
        palette2.setBrush(QPalette.Disabled, QPalette.Window, brush12)
        palette2.setBrush(QPalette.Disabled, QPalette.Shadow, brush7)
        palette2.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush10)
        palette2.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette2.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush7)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush9)
#endif
        self.score_value.setPalette(palette2)
        font2 = QFont()
        font2.setFamilies([u"Montserrat Medium"])
        font2.setPointSize(12)
        font2.setBold(False)
        self.score_value.setFont(font2)
        self.score_value.setStyleSheet(u"color: rgb(217, 66, 39);")
        self.widget = QWidget(Form)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(19, 89, 761, 411))
        self.widget.setStyleSheet(u"background-color: rgb(255, 246, 235);\n"
"border-radius: 10 px;")
        self.label = QLabel(self.widget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(280, 20, 181, 41))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush11)
        palette3.setBrush(QPalette.Active, QPalette.Button, brush12)
        palette3.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette3.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette3.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette3.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette3.setBrush(QPalette.Active, QPalette.Text, brush11)
        palette3.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette3.setBrush(QPalette.Active, QPalette.ButtonText, brush11)
        palette3.setBrush(QPalette.Active, QPalette.Base, brush12)
        palette3.setBrush(QPalette.Active, QPalette.Window, brush12)
        palette3.setBrush(QPalette.Active, QPalette.Shadow, brush7)
        palette3.setBrush(QPalette.Active, QPalette.AlternateBase, brush4)
        palette3.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette3.setBrush(QPalette.Active, QPalette.ToolTipText, brush7)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Active, QPalette.PlaceholderText, brush9)
#endif
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush11)
        palette3.setBrush(QPalette.Inactive, QPalette.Button, brush12)
        palette3.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette3.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette3.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette3.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette3.setBrush(QPalette.Inactive, QPalette.Text, brush11)
        palette3.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette3.setBrush(QPalette.Inactive, QPalette.ButtonText, brush11)
        palette3.setBrush(QPalette.Inactive, QPalette.Base, brush12)
        palette3.setBrush(QPalette.Inactive, QPalette.Window, brush12)
        palette3.setBrush(QPalette.Inactive, QPalette.Shadow, brush7)
        palette3.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush4)
        palette3.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette3.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush7)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush9)
#endif
        palette3.setBrush(QPalette.Disabled, QPalette.WindowText, brush11)
        palette3.setBrush(QPalette.Disabled, QPalette.Button, brush12)
        palette3.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette3.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette3.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette3.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette3.setBrush(QPalette.Disabled, QPalette.Text, brush11)
        palette3.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette3.setBrush(QPalette.Disabled, QPalette.ButtonText, brush11)
        palette3.setBrush(QPalette.Disabled, QPalette.Base, brush12)
        palette3.setBrush(QPalette.Disabled, QPalette.Window, brush12)
        palette3.setBrush(QPalette.Disabled, QPalette.Shadow, brush7)
        palette3.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush10)
        palette3.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette3.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush7)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush9)
#endif
        self.label.setPalette(palette3)
        font3 = QFont()
        font3.setFamilies([u"Elephant"])
        font3.setPointSize(20)
        self.label.setFont(font3)
        self.label.setStyleSheet(u"color: rgb(217, 66, 39);\n"
"background-color: rgb(255, 246, 235);")
        self.label.setAlignment(Qt.AlignCenter)
        self.exit_btn = QPushButton(self.widget)
        self.exit_btn.setObjectName(u"exit_btn")
        self.exit_btn.setGeometry(QRect(50, 350, 161, 41))
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.WindowText, brush7)
        brush13 = QBrush(QColor(255, 221, 188, 255))
        brush13.setStyle(Qt.SolidPattern)
        palette4.setBrush(QPalette.Active, QPalette.Button, brush13)
        brush14 = QBrush(QColor(139, 255, 176, 255))
        brush14.setStyle(Qt.SolidPattern)
        palette4.setBrush(QPalette.Active, QPalette.Light, brush14)
        brush15 = QBrush(QColor(115, 213, 146, 255))
        brush15.setStyle(Qt.SolidPattern)
        palette4.setBrush(QPalette.Active, QPalette.Midlight, brush15)
        brush16 = QBrush(QColor(46, 85, 59, 255))
        brush16.setStyle(Qt.SolidPattern)
        palette4.setBrush(QPalette.Active, QPalette.Dark, brush16)
        brush17 = QBrush(QColor(61, 114, 78, 255))
        brush17.setStyle(Qt.SolidPattern)
        palette4.setBrush(QPalette.Active, QPalette.Mid, brush17)
        palette4.setBrush(QPalette.Active, QPalette.Text, brush7)
        palette4.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette4.setBrush(QPalette.Active, QPalette.ButtonText, brush7)
        palette4.setBrush(QPalette.Active, QPalette.Base, brush13)
        palette4.setBrush(QPalette.Active, QPalette.Window, brush13)
        palette4.setBrush(QPalette.Active, QPalette.Shadow, brush7)
        brush18 = QBrush(QColor(173, 213, 186, 255))
        brush18.setStyle(Qt.SolidPattern)
        palette4.setBrush(QPalette.Active, QPalette.AlternateBase, brush18)
        palette4.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette4.setBrush(QPalette.Active, QPalette.ToolTipText, brush7)
        brush19 = QBrush(QColor(0, 0, 0, 128))
        brush19.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Active, QPalette.PlaceholderText, brush19)
#endif
        palette4.setBrush(QPalette.Inactive, QPalette.WindowText, brush7)
        palette4.setBrush(QPalette.Inactive, QPalette.Button, brush13)
        palette4.setBrush(QPalette.Inactive, QPalette.Light, brush14)
        palette4.setBrush(QPalette.Inactive, QPalette.Midlight, brush15)
        palette4.setBrush(QPalette.Inactive, QPalette.Dark, brush16)
        palette4.setBrush(QPalette.Inactive, QPalette.Mid, brush17)
        palette4.setBrush(QPalette.Inactive, QPalette.Text, brush7)
        palette4.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette4.setBrush(QPalette.Inactive, QPalette.ButtonText, brush7)
        palette4.setBrush(QPalette.Inactive, QPalette.Base, brush13)
        palette4.setBrush(QPalette.Inactive, QPalette.Window, brush13)
        palette4.setBrush(QPalette.Inactive, QPalette.Shadow, brush7)
        palette4.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush18)
        palette4.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette4.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush7)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush19)
#endif
        palette4.setBrush(QPalette.Disabled, QPalette.WindowText, brush7)
        palette4.setBrush(QPalette.Disabled, QPalette.Button, brush13)
        palette4.setBrush(QPalette.Disabled, QPalette.Light, brush14)
        palette4.setBrush(QPalette.Disabled, QPalette.Midlight, brush15)
        palette4.setBrush(QPalette.Disabled, QPalette.Dark, brush16)
        palette4.setBrush(QPalette.Disabled, QPalette.Mid, brush17)
        palette4.setBrush(QPalette.Disabled, QPalette.Text, brush7)
        palette4.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette4.setBrush(QPalette.Disabled, QPalette.ButtonText, brush7)
        palette4.setBrush(QPalette.Disabled, QPalette.Base, brush13)
        palette4.setBrush(QPalette.Disabled, QPalette.Window, brush13)
        palette4.setBrush(QPalette.Disabled, QPalette.Shadow, brush7)
        brush20 = QBrush(QColor(92, 171, 117, 255))
        brush20.setStyle(Qt.SolidPattern)
        palette4.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush20)
        palette4.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette4.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush7)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush19)
#endif
        self.exit_btn.setPalette(palette4)
        font4 = QFont()
        font4.setFamilies([u"Montserrat Medium"])
        font4.setPointSize(9)
        font4.setBold(False)
        font4.setItalic(True)
        self.exit_btn.setFont(font4)
        self.exit_btn.setStyleSheet(u"QPushButton{\n"
"background-color: rgb(255, 221, 188);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"border: 3px solid;\n"
"border-color: rgb(167, 29, 34);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed{\n"
"border: 6px solid;\n"
"border-color: rgb(255, 132, 32);\n"
"}")
        self.label_8 = QLabel(self.widget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(60, 360, 21, 21))
        self.label_8.setStyleSheet(u"background-color: rgb(255, 221, 188);")
        self.label_8.setPixmap(QPixmap(u":/Icons/home-1-svgrepo-com.svg"))
        self.label_8.setScaledContents(True)
        self.start_button = QPushButton(self.widget)
        self.start_button.setObjectName(u"start_button")
        self.start_button.setGeometry(QRect(50, 200, 161, 51))
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.WindowText, brush7)
        palette5.setBrush(QPalette.Active, QPalette.Button, brush13)
        palette5.setBrush(QPalette.Active, QPalette.Light, brush14)
        palette5.setBrush(QPalette.Active, QPalette.Midlight, brush15)
        palette5.setBrush(QPalette.Active, QPalette.Dark, brush16)
        palette5.setBrush(QPalette.Active, QPalette.Mid, brush17)
        palette5.setBrush(QPalette.Active, QPalette.Text, brush7)
        palette5.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette5.setBrush(QPalette.Active, QPalette.ButtonText, brush7)
        palette5.setBrush(QPalette.Active, QPalette.Base, brush13)
        palette5.setBrush(QPalette.Active, QPalette.Window, brush13)
        palette5.setBrush(QPalette.Active, QPalette.Shadow, brush7)
        palette5.setBrush(QPalette.Active, QPalette.AlternateBase, brush18)
        palette5.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette5.setBrush(QPalette.Active, QPalette.ToolTipText, brush7)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette.Active, QPalette.PlaceholderText, brush19)
#endif
        palette5.setBrush(QPalette.Inactive, QPalette.WindowText, brush7)
        palette5.setBrush(QPalette.Inactive, QPalette.Button, brush13)
        palette5.setBrush(QPalette.Inactive, QPalette.Light, brush14)
        palette5.setBrush(QPalette.Inactive, QPalette.Midlight, brush15)
        palette5.setBrush(QPalette.Inactive, QPalette.Dark, brush16)
        palette5.setBrush(QPalette.Inactive, QPalette.Mid, brush17)
        palette5.setBrush(QPalette.Inactive, QPalette.Text, brush7)
        palette5.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette5.setBrush(QPalette.Inactive, QPalette.ButtonText, brush7)
        palette5.setBrush(QPalette.Inactive, QPalette.Base, brush13)
        palette5.setBrush(QPalette.Inactive, QPalette.Window, brush13)
        palette5.setBrush(QPalette.Inactive, QPalette.Shadow, brush7)
        palette5.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush18)
        palette5.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette5.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush7)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush19)
#endif
        palette5.setBrush(QPalette.Disabled, QPalette.WindowText, brush16)
        palette5.setBrush(QPalette.Disabled, QPalette.Button, brush13)
        palette5.setBrush(QPalette.Disabled, QPalette.Light, brush14)
        palette5.setBrush(QPalette.Disabled, QPalette.Midlight, brush15)
        palette5.setBrush(QPalette.Disabled, QPalette.Dark, brush16)
        palette5.setBrush(QPalette.Disabled, QPalette.Mid, brush17)
        palette5.setBrush(QPalette.Disabled, QPalette.Text, brush16)
        palette5.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette5.setBrush(QPalette.Disabled, QPalette.ButtonText, brush16)
        palette5.setBrush(QPalette.Disabled, QPalette.Base, brush13)
        palette5.setBrush(QPalette.Disabled, QPalette.Window, brush13)
        palette5.setBrush(QPalette.Disabled, QPalette.Shadow, brush7)
        palette5.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush20)
        palette5.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette5.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush7)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush19)
#endif
        self.start_button.setPalette(palette5)
        font5 = QFont()
        font5.setFamilies([u"Montserrat SemiBold"])
        font5.setPointSize(12)
        font5.setBold(True)
        self.start_button.setFont(font5)
        self.start_button.setStyleSheet(u"QPushButton{\n"
"background-color: rgb(255, 221, 188);\n"
"border-radius: 10px;\n"
"border: 3px solid;\n"
"border-color: rgb(167, 29, 34);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed{\n"
"border: 6px solid;\n"
"border-color: rgb(255, 132, 32);\n"
"}\n"
"")
        self.tryagain_label = QLabel(self.widget)
        self.tryagain_label.setObjectName(u"tryagain_label")
        self.tryagain_label.setGeometry(QRect(260, 280, 231, 41))
        font6 = QFont()
        font6.setFamilies([u"Elephant"])
        font6.setPointSize(16)
        font6.setBold(False)
        self.tryagain_label.setFont(font6)
        self.tryagain_label.setStyleSheet(u"color: rgb(217, 66, 39);")
        self.greatjob_label = QLabel(self.widget)
        self.greatjob_label.setObjectName(u"greatjob_label")
        self.greatjob_label.setGeometry(QRect(300, 280, 141, 41))
        font7 = QFont()
        font7.setFamilies([u"Elephant"])
        font7.setPointSize(16)
        self.greatjob_label.setFont(font7)
        self.greatjob_label.setStyleSheet(u"color: rgb(217, 66, 39);")
        self.countdown_label = QLabel(self.widget)
        self.countdown_label.setObjectName(u"countdown_label")
        self.countdown_label.setGeometry(QRect(330, 120, 71, 81))
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.WindowText, brush4)
        palette6.setBrush(QPalette.Active, QPalette.Button, brush12)
        palette6.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette6.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette6.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette6.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette6.setBrush(QPalette.Active, QPalette.Text, brush4)
        palette6.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette6.setBrush(QPalette.Active, QPalette.ButtonText, brush4)
        palette6.setBrush(QPalette.Active, QPalette.Base, brush12)
        palette6.setBrush(QPalette.Active, QPalette.Window, brush12)
        palette6.setBrush(QPalette.Active, QPalette.Shadow, brush7)
        palette6.setBrush(QPalette.Active, QPalette.AlternateBase, brush4)
        palette6.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette6.setBrush(QPalette.Active, QPalette.ToolTipText, brush7)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette.Active, QPalette.PlaceholderText, brush9)
#endif
        palette6.setBrush(QPalette.Inactive, QPalette.WindowText, brush4)
        palette6.setBrush(QPalette.Inactive, QPalette.Button, brush12)
        palette6.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette6.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette6.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette6.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette6.setBrush(QPalette.Inactive, QPalette.Text, brush4)
        palette6.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette6.setBrush(QPalette.Inactive, QPalette.ButtonText, brush4)
        palette6.setBrush(QPalette.Inactive, QPalette.Base, brush12)
        palette6.setBrush(QPalette.Inactive, QPalette.Window, brush12)
        palette6.setBrush(QPalette.Inactive, QPalette.Shadow, brush7)
        palette6.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush4)
        palette6.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette6.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush7)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush9)
#endif
        palette6.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette6.setBrush(QPalette.Disabled, QPalette.Button, brush12)
        palette6.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette6.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette6.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette6.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette6.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette6.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette6.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette6.setBrush(QPalette.Disabled, QPalette.Base, brush12)
        palette6.setBrush(QPalette.Disabled, QPalette.Window, brush12)
        palette6.setBrush(QPalette.Disabled, QPalette.Shadow, brush7)
        palette6.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush10)
        palette6.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette6.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush7)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush9)
#endif
        self.countdown_label.setPalette(palette6)
        font8 = QFont()
        font8.setFamilies([u"Montserrat Medium"])
        font8.setPointSize(26)
        font8.setBold(False)
        self.countdown_label.setFont(font8)
        self.countdown_label.setStyleSheet(u"background-color: rgb(255, 246, 235);\n"
"color: rgb(0, 46, 0);")
        self.countdown_label.setAlignment(Qt.AlignCenter)
        self.seconds_label = QLabel(self.widget)
        self.seconds_label.setObjectName(u"seconds_label")
        self.seconds_label.setGeometry(QRect(280, 90, 171, 27))
        palette7 = QPalette()
        palette7.setBrush(QPalette.Active, QPalette.WindowText, brush7)
        palette7.setBrush(QPalette.Active, QPalette.Button, brush12)
        palette7.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette7.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette7.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette7.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette7.setBrush(QPalette.Active, QPalette.Text, brush7)
        palette7.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette7.setBrush(QPalette.Active, QPalette.ButtonText, brush7)
        palette7.setBrush(QPalette.Active, QPalette.Base, brush12)
        palette7.setBrush(QPalette.Active, QPalette.Window, brush12)
        palette7.setBrush(QPalette.Active, QPalette.Shadow, brush7)
        palette7.setBrush(QPalette.Active, QPalette.AlternateBase, brush4)
        palette7.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette7.setBrush(QPalette.Active, QPalette.ToolTipText, brush7)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette.Active, QPalette.PlaceholderText, brush9)
#endif
        palette7.setBrush(QPalette.Inactive, QPalette.WindowText, brush7)
        palette7.setBrush(QPalette.Inactive, QPalette.Button, brush12)
        palette7.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette7.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette7.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette7.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette7.setBrush(QPalette.Inactive, QPalette.Text, brush7)
        palette7.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette7.setBrush(QPalette.Inactive, QPalette.ButtonText, brush7)
        palette7.setBrush(QPalette.Inactive, QPalette.Base, brush12)
        palette7.setBrush(QPalette.Inactive, QPalette.Window, brush12)
        palette7.setBrush(QPalette.Inactive, QPalette.Shadow, brush7)
        palette7.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush4)
        palette7.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette7.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush7)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush9)
#endif
        palette7.setBrush(QPalette.Disabled, QPalette.WindowText, brush7)
        palette7.setBrush(QPalette.Disabled, QPalette.Button, brush12)
        palette7.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette7.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette7.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette7.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette7.setBrush(QPalette.Disabled, QPalette.Text, brush7)
        palette7.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette7.setBrush(QPalette.Disabled, QPalette.ButtonText, brush7)
        palette7.setBrush(QPalette.Disabled, QPalette.Base, brush12)
        palette7.setBrush(QPalette.Disabled, QPalette.Window, brush12)
        palette7.setBrush(QPalette.Disabled, QPalette.Shadow, brush7)
        palette7.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush10)
        palette7.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette7.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush7)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush9)
#endif
        self.seconds_label.setPalette(palette7)
        self.seconds_label.setFont(font5)
        self.seconds_label.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.seconds_label.setAlignment(Qt.AlignCenter)
        self.label_2 = QLabel(self.widget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(520, 350, 31, 31))
        self.label_2.setStyleSheet(u"background-color: rgb(255, 221, 188);")
        self.label_2.setPixmap(QPixmap(u":/Icons/find-svgrepo-com.svg"))
        self.label_2.setScaledContents(True)
        self.solution_button = QPushButton(self.widget)
        self.solution_button.setObjectName(u"solution_button")
        self.solution_button.setGeometry(QRect(510, 340, 221, 51))
        palette8 = QPalette()
        palette8.setBrush(QPalette.Active, QPalette.WindowText, brush7)
        palette8.setBrush(QPalette.Active, QPalette.Button, brush13)
        palette8.setBrush(QPalette.Active, QPalette.Light, brush14)
        palette8.setBrush(QPalette.Active, QPalette.Midlight, brush15)
        palette8.setBrush(QPalette.Active, QPalette.Dark, brush16)
        palette8.setBrush(QPalette.Active, QPalette.Mid, brush17)
        palette8.setBrush(QPalette.Active, QPalette.Text, brush7)
        palette8.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette8.setBrush(QPalette.Active, QPalette.ButtonText, brush7)
        palette8.setBrush(QPalette.Active, QPalette.Base, brush13)
        palette8.setBrush(QPalette.Active, QPalette.Window, brush13)
        palette8.setBrush(QPalette.Active, QPalette.Shadow, brush7)
        palette8.setBrush(QPalette.Active, QPalette.AlternateBase, brush18)
        palette8.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette8.setBrush(QPalette.Active, QPalette.ToolTipText, brush7)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette8.setBrush(QPalette.Active, QPalette.PlaceholderText, brush19)
#endif
        palette8.setBrush(QPalette.Inactive, QPalette.WindowText, brush7)
        palette8.setBrush(QPalette.Inactive, QPalette.Button, brush13)
        palette8.setBrush(QPalette.Inactive, QPalette.Light, brush14)
        palette8.setBrush(QPalette.Inactive, QPalette.Midlight, brush15)
        palette8.setBrush(QPalette.Inactive, QPalette.Dark, brush16)
        palette8.setBrush(QPalette.Inactive, QPalette.Mid, brush17)
        palette8.setBrush(QPalette.Inactive, QPalette.Text, brush7)
        palette8.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette8.setBrush(QPalette.Inactive, QPalette.ButtonText, brush7)
        palette8.setBrush(QPalette.Inactive, QPalette.Base, brush13)
        palette8.setBrush(QPalette.Inactive, QPalette.Window, brush13)
        palette8.setBrush(QPalette.Inactive, QPalette.Shadow, brush7)
        palette8.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush18)
        palette8.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette8.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush7)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette8.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush19)
#endif
        palette8.setBrush(QPalette.Disabled, QPalette.WindowText, brush7)
        palette8.setBrush(QPalette.Disabled, QPalette.Button, brush13)
        palette8.setBrush(QPalette.Disabled, QPalette.Light, brush14)
        palette8.setBrush(QPalette.Disabled, QPalette.Midlight, brush15)
        palette8.setBrush(QPalette.Disabled, QPalette.Dark, brush16)
        palette8.setBrush(QPalette.Disabled, QPalette.Mid, brush17)
        palette8.setBrush(QPalette.Disabled, QPalette.Text, brush7)
        palette8.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette8.setBrush(QPalette.Disabled, QPalette.ButtonText, brush7)
        palette8.setBrush(QPalette.Disabled, QPalette.Base, brush13)
        palette8.setBrush(QPalette.Disabled, QPalette.Window, brush13)
        palette8.setBrush(QPalette.Disabled, QPalette.Shadow, brush7)
        palette8.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush20)
        palette8.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette8.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush7)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette8.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush19)
#endif
        self.solution_button.setPalette(palette8)
        font9 = QFont()
        font9.setFamilies([u"Montserrat SemiBold"])
        font9.setPointSize(10)
        font9.setBold(True)
        self.solution_button.setFont(font9)
        self.solution_button.setStyleSheet(u"QPushButton{\n"
"background-color: rgb(255, 221, 188);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"border: 3px solid;\n"
"border-color: rgb(167, 29, 34);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed{\n"
"border: 6px solid;\n"
"border-color: rgb(255, 132, 32);\n"
"}")
        self.StayStill_label = QLabel(self.widget)
        self.StayStill_label.setObjectName(u"StayStill_label")
        self.StayStill_label.setGeometry(QRect(290, 190, 151, 61))
        font10 = QFont()
        font10.setFamilies([u"Montserrat Medium"])
        font10.setPointSize(18)
        self.StayStill_label.setFont(font10)
        self.StayStill_label.setAlignment(Qt.AlignCenter)
        self.image_label = QLabel(self.widget)
        self.image_label.setObjectName(u"image_label")
        self.image_label.setGeometry(QRect(550, 90, 131, 171))
        self.image_label.setStyleSheet(u"background-color: rgb(255, 246, 235);")
        self.image_label.setAlignment(Qt.AlignCenter)
        self.calibration_btn = QPushButton(self.widget)
        self.calibration_btn.setObjectName(u"calibration_btn")
        self.calibration_btn.setGeometry(QRect(50, 270, 161, 51))
        self.calibration_btn.setFont(font5)
        self.calibration_btn.setStyleSheet(u"QPushButton{\n"
"background-color: rgb(255, 221, 188);\n"
"border-radius: 10px;\n"
"border: 3px solid;\n"
"border-color: rgb(167, 29, 34);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed{\n"
"border: 6px solid;\n"
"border-color: rgb(255, 132, 32);\n"
"}")
        self.classified_target = QLabel(self.widget)
        self.classified_target.setObjectName(u"classified_target")
        self.classified_target.setGeometry(QRect(190, 120, 31, 27))
        palette9 = QPalette()
        palette9.setBrush(QPalette.Active, QPalette.WindowText, brush7)
        palette9.setBrush(QPalette.Active, QPalette.Button, brush12)
        palette9.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette9.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette9.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette9.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette9.setBrush(QPalette.Active, QPalette.Text, brush7)
        palette9.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette9.setBrush(QPalette.Active, QPalette.ButtonText, brush7)
        palette9.setBrush(QPalette.Active, QPalette.Base, brush12)
        palette9.setBrush(QPalette.Active, QPalette.Window, brush12)
        palette9.setBrush(QPalette.Active, QPalette.Shadow, brush7)
        palette9.setBrush(QPalette.Active, QPalette.AlternateBase, brush4)
        palette9.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette9.setBrush(QPalette.Active, QPalette.ToolTipText, brush7)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette9.setBrush(QPalette.Active, QPalette.PlaceholderText, brush9)
#endif
        palette9.setBrush(QPalette.Inactive, QPalette.WindowText, brush7)
        palette9.setBrush(QPalette.Inactive, QPalette.Button, brush12)
        palette9.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette9.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette9.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette9.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette9.setBrush(QPalette.Inactive, QPalette.Text, brush7)
        palette9.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette9.setBrush(QPalette.Inactive, QPalette.ButtonText, brush7)
        palette9.setBrush(QPalette.Inactive, QPalette.Base, brush12)
        palette9.setBrush(QPalette.Inactive, QPalette.Window, brush12)
        palette9.setBrush(QPalette.Inactive, QPalette.Shadow, brush7)
        palette9.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush4)
        palette9.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette9.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush7)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette9.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush9)
#endif
        palette9.setBrush(QPalette.Disabled, QPalette.WindowText, brush7)
        palette9.setBrush(QPalette.Disabled, QPalette.Button, brush12)
        palette9.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette9.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette9.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette9.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette9.setBrush(QPalette.Disabled, QPalette.Text, brush7)
        palette9.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette9.setBrush(QPalette.Disabled, QPalette.ButtonText, brush7)
        palette9.setBrush(QPalette.Disabled, QPalette.Base, brush12)
        palette9.setBrush(QPalette.Disabled, QPalette.Window, brush12)
        palette9.setBrush(QPalette.Disabled, QPalette.Shadow, brush7)
        palette9.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush10)
        palette9.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette9.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush7)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette9.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush9)
#endif
        self.classified_target.setPalette(palette9)
        self.classified_target.setFont(font5)
        self.classified_target.setStyleSheet(u"background-color: rgb(255, 246, 235);\n"
"color: rgb(0, 0, 0);\n"
"border-color: rgb(254, 245, 234);")
        self.letter_target = QLabel(self.widget)
        self.letter_target.setObjectName(u"letter_target")
        self.letter_target.setGeometry(QRect(190, 60, 31, 31))
        palette10 = QPalette()
        palette10.setBrush(QPalette.Active, QPalette.WindowText, brush7)
        palette10.setBrush(QPalette.Active, QPalette.Button, brush12)
        palette10.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette10.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette10.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette10.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette10.setBrush(QPalette.Active, QPalette.Text, brush7)
        palette10.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette10.setBrush(QPalette.Active, QPalette.ButtonText, brush7)
        palette10.setBrush(QPalette.Active, QPalette.Base, brush12)
        palette10.setBrush(QPalette.Active, QPalette.Window, brush12)
        palette10.setBrush(QPalette.Active, QPalette.Shadow, brush7)
        palette10.setBrush(QPalette.Active, QPalette.AlternateBase, brush4)
        palette10.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette10.setBrush(QPalette.Active, QPalette.ToolTipText, brush7)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette10.setBrush(QPalette.Active, QPalette.PlaceholderText, brush9)
#endif
        palette10.setBrush(QPalette.Inactive, QPalette.WindowText, brush7)
        palette10.setBrush(QPalette.Inactive, QPalette.Button, brush12)
        palette10.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette10.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette10.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette10.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette10.setBrush(QPalette.Inactive, QPalette.Text, brush7)
        palette10.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette10.setBrush(QPalette.Inactive, QPalette.ButtonText, brush7)
        palette10.setBrush(QPalette.Inactive, QPalette.Base, brush12)
        palette10.setBrush(QPalette.Inactive, QPalette.Window, brush12)
        palette10.setBrush(QPalette.Inactive, QPalette.Shadow, brush7)
        palette10.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush4)
        palette10.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette10.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush7)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette10.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush9)
#endif
        palette10.setBrush(QPalette.Disabled, QPalette.WindowText, brush7)
        palette10.setBrush(QPalette.Disabled, QPalette.Button, brush12)
        palette10.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette10.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette10.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette10.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette10.setBrush(QPalette.Disabled, QPalette.Text, brush7)
        palette10.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette10.setBrush(QPalette.Disabled, QPalette.ButtonText, brush7)
        palette10.setBrush(QPalette.Disabled, QPalette.Base, brush12)
        palette10.setBrush(QPalette.Disabled, QPalette.Window, brush12)
        palette10.setBrush(QPalette.Disabled, QPalette.Shadow, brush7)
        palette10.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush10)
        palette10.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette10.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush7)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette10.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush9)
#endif
        self.letter_target.setPalette(palette10)
        self.letter_target.setFont(font5)
        self.letter_target.setStyleSheet(u"background-color: rgb(255, 246, 235);\n"
"color: rgb(0, 0, 0);\n"
"border-color: rgb(254, 245, 234);")
        self.class_label = QLabel(self.widget)
        self.class_label.setObjectName(u"class_label")
        self.class_label.setGeometry(QRect(60, 120, 101, 27))
        palette11 = QPalette()
        palette11.setBrush(QPalette.Active, QPalette.WindowText, brush7)
        palette11.setBrush(QPalette.Active, QPalette.Button, brush12)
        palette11.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette11.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette11.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette11.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette11.setBrush(QPalette.Active, QPalette.Text, brush7)
        palette11.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette11.setBrush(QPalette.Active, QPalette.ButtonText, brush7)
        palette11.setBrush(QPalette.Active, QPalette.Base, brush12)
        palette11.setBrush(QPalette.Active, QPalette.Window, brush12)
        palette11.setBrush(QPalette.Active, QPalette.Shadow, brush7)
        palette11.setBrush(QPalette.Active, QPalette.AlternateBase, brush4)
        palette11.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette11.setBrush(QPalette.Active, QPalette.ToolTipText, brush7)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette11.setBrush(QPalette.Active, QPalette.PlaceholderText, brush9)
#endif
        palette11.setBrush(QPalette.Inactive, QPalette.WindowText, brush7)
        palette11.setBrush(QPalette.Inactive, QPalette.Button, brush12)
        palette11.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette11.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette11.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette11.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette11.setBrush(QPalette.Inactive, QPalette.Text, brush7)
        palette11.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette11.setBrush(QPalette.Inactive, QPalette.ButtonText, brush7)
        palette11.setBrush(QPalette.Inactive, QPalette.Base, brush12)
        palette11.setBrush(QPalette.Inactive, QPalette.Window, brush12)
        palette11.setBrush(QPalette.Inactive, QPalette.Shadow, brush7)
        palette11.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush4)
        palette11.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette11.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush7)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette11.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush9)
#endif
        palette11.setBrush(QPalette.Disabled, QPalette.WindowText, brush7)
        palette11.setBrush(QPalette.Disabled, QPalette.Button, brush12)
        palette11.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette11.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette11.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette11.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette11.setBrush(QPalette.Disabled, QPalette.Text, brush7)
        palette11.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette11.setBrush(QPalette.Disabled, QPalette.ButtonText, brush7)
        palette11.setBrush(QPalette.Disabled, QPalette.Base, brush12)
        palette11.setBrush(QPalette.Disabled, QPalette.Window, brush12)
        palette11.setBrush(QPalette.Disabled, QPalette.Shadow, brush7)
        palette11.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush10)
        palette11.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette11.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush7)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette11.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush9)
#endif
        self.class_label.setPalette(palette11)
        self.class_label.setFont(font5)
        self.class_label.setStyleSheet(u"background-color: rgb(255, 246, 235);\n"
"color: rgb(0, 0, 0);\n"
"border-color: rgb(254, 245, 234);")
        self.letter_label = QLabel(self.widget)
        self.letter_label.setObjectName(u"letter_label")
        self.letter_label.setGeometry(QRect(54, 62, 111, 31))
        palette12 = QPalette()
        palette12.setBrush(QPalette.Active, QPalette.WindowText, brush7)
        palette12.setBrush(QPalette.Active, QPalette.Button, brush12)
        palette12.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette12.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette12.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette12.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette12.setBrush(QPalette.Active, QPalette.Text, brush7)
        palette12.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette12.setBrush(QPalette.Active, QPalette.ButtonText, brush7)
        palette12.setBrush(QPalette.Active, QPalette.Base, brush12)
        palette12.setBrush(QPalette.Active, QPalette.Window, brush12)
        palette12.setBrush(QPalette.Active, QPalette.Shadow, brush7)
        palette12.setBrush(QPalette.Active, QPalette.AlternateBase, brush4)
        palette12.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette12.setBrush(QPalette.Active, QPalette.ToolTipText, brush7)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette12.setBrush(QPalette.Active, QPalette.PlaceholderText, brush9)
#endif
        palette12.setBrush(QPalette.Inactive, QPalette.WindowText, brush7)
        palette12.setBrush(QPalette.Inactive, QPalette.Button, brush12)
        palette12.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette12.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette12.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette12.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette12.setBrush(QPalette.Inactive, QPalette.Text, brush7)
        palette12.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette12.setBrush(QPalette.Inactive, QPalette.ButtonText, brush7)
        palette12.setBrush(QPalette.Inactive, QPalette.Base, brush12)
        palette12.setBrush(QPalette.Inactive, QPalette.Window, brush12)
        palette12.setBrush(QPalette.Inactive, QPalette.Shadow, brush7)
        palette12.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush4)
        palette12.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette12.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush7)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette12.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush9)
#endif
        palette12.setBrush(QPalette.Disabled, QPalette.WindowText, brush7)
        palette12.setBrush(QPalette.Disabled, QPalette.Button, brush12)
        palette12.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette12.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette12.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette12.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette12.setBrush(QPalette.Disabled, QPalette.Text, brush7)
        palette12.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette12.setBrush(QPalette.Disabled, QPalette.ButtonText, brush7)
        palette12.setBrush(QPalette.Disabled, QPalette.Base, brush12)
        palette12.setBrush(QPalette.Disabled, QPalette.Window, brush12)
        palette12.setBrush(QPalette.Disabled, QPalette.Shadow, brush7)
        palette12.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush10)
        palette12.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette12.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush7)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette12.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush9)
#endif
        self.letter_label.setPalette(palette12)
        self.letter_label.setFont(font5)
        self.letter_label.setStyleSheet(u"background-color: rgb(255, 246, 235);\n"
"color: rgb(0, 0, 0);\n"
"border-color: rgb(254, 245, 234);")
        self.letter_label.setAlignment(Qt.AlignCenter)
        self.label.raise_()
        self.exit_btn.raise_()
        self.label_8.raise_()
        self.start_button.raise_()
        self.tryagain_label.raise_()
        self.greatjob_label.raise_()
        self.countdown_label.raise_()
        self.seconds_label.raise_()
        self.solution_button.raise_()
        self.label_2.raise_()
        self.StayStill_label.raise_()
        self.image_label.raise_()
        self.calibration_btn.raise_()
        self.classified_target.raise_()
        self.letter_target.raise_()
        self.class_label.raise_()
        self.letter_label.raise_()
        self.widget.raise_()
        self.frame_3.raise_()

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.Username_label.setText(QCoreApplication.translate("Form", u"Username", None))
        self.label_5.setText("")
        self.label_6.setText("")
        self.label_7.setText(QCoreApplication.translate("Form", u"Level 1", None))
        self.score_label.setText(QCoreApplication.translate("Form", u"Score:", None))
        self.score_value.setText(QCoreApplication.translate("Form", u"0", None))
        self.label.setText(QCoreApplication.translate("Form", u"Let's play!", None))
        self.exit_btn.setText(QCoreApplication.translate("Form", u"      Back to Menu", None))
        self.label_8.setText("")
        self.start_button.setText(QCoreApplication.translate("Form", u"Start", None))
        self.tryagain_label.setText(QCoreApplication.translate("Form", u"Oh no, try again", None))
        self.greatjob_label.setText(QCoreApplication.translate("Form", u"Great job!", None))
        self.countdown_label.setText(QCoreApplication.translate("Form", u"2", None))
        self.seconds_label.setText(QCoreApplication.translate("Form", u"Seconds Left:", None))
        self.label_2.setText("")
        self.solution_button.setText(QCoreApplication.translate("Form", u"      See the solution", None))
        self.StayStill_label.setText(QCoreApplication.translate("Form", u"Stay Still", None))
        self.image_label.setText("")
        self.calibration_btn.setText(QCoreApplication.translate("Form", u"Calibrate", None))
        self.classified_target.setText(QCoreApplication.translate("Form", u"?", None))
        self.letter_target.setText(QCoreApplication.translate("Form", u"?", None))
        self.class_label.setText(QCoreApplication.translate("Form", u"You did: ", None))
        self.letter_label.setText(QCoreApplication.translate("Form", u"Try to do: ", None))
    # retranslateUi

