# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Utente\Desktop\AY2223_II_Project-4\Software\Menu_Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(492, 499)
        Form.setStyleSheet("QWidget{background-color: rgb(255, 215, 179);}\n"
"\n"
"#play_button:hover {background-color: rgb(167, 29, 34);}")
        self.statistics_button = QtWidgets.QPushButton(Form)
        self.statistics_button.setGeometry(QtCore.QRect(100, 320, 291, 61))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.statistics_button.setFont(font)
        self.statistics_button.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 221, 188);\n"
"border-radius: 10px;\n"
"border: 3px solid;\n"
"border-color: rgb(167, 29, 34);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed{\n"
"border: 6px solid;\n"
"border-color: rgb(255, 132, 32);\n"
"}")
        self.statistics_button.setObjectName("statistics_button")
        self.play_button = QtWidgets.QPushButton(Form)
        self.play_button.setGeometry(QtCore.QRect(100, 250, 291, 61))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.play_button.setFont(font)
        self.play_button.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 221, 188);\n"
"border-radius: 10px;\n"
"border: 3px solid;\n"
"border-color: rgb(166, 30, 34);\n"
"}\n"
"QPushButton:hover:!pressed{\n"
"border: 6px solid;\n"
"border-color: rgb(255, 132, 32);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.play_button.setFlat(False)
        self.play_button.setObjectName("play_button")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 491, 281))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/Images/Download Hello Hand Sign Language Concept for free.jpeg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(130, 260, 51, 41))
        self.label_2.setStyleSheet("QLabel{\n"
"background-color: rgb(255, 221, 188);\n"
"}\n"
"\n"
"")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/Icons/fight-svgrepo-com.svg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(130, 330, 41, 41))
        self.label_3.setStyleSheet("background-color: rgb(255, 221, 188);\n"
"color: rgb(0, 0, 0);")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/Icons/increase-svgrepo-com.svg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.log_out_btn = QtWidgets.QPushButton(Form)
        self.log_out_btn.setGeometry(QtCore.QRect(100, 390, 291, 61))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.log_out_btn.setFont(font)
        self.log_out_btn.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 221, 188);\n"
"border-radius: 10px;\n"
"border: 3px solid;\n"
"border-color: rgb(167, 29, 34);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed{\n"
"border: 6px solid;\n"
"border-color: rgb(255, 132, 32);\n"
"}")
        self.log_out_btn.setObjectName("log_out_btn")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(130, 400, 41, 41))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/Icons/logout-svgrepo-com.svg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label.raise_()
        self.statistics_button.raise_()
        self.play_button.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.log_out_btn.raise_()
        self.label_4.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.statistics_button.setText(_translate("Form", "      Statistics"))
        self.play_button.setText(_translate("Form", "         New Game"))
        self.log_out_btn.setText(_translate("Form", "      Log out"))
import ResourceFiles_rc
